apiVersion: v1alpha
kind: xctest
sauce:
  concurrency: 1
xctest:
  app: ./app_binaries/fake_counter_all_binaries/FakeCounterApp.ipa
  xcTestRunFile: ./app_binaries/fake_counter_xctestrun_file/xctest_and_xcuitest_xctestrin_file/FakeCounterAppTest_mix_xcuitest_and_xctest_are_configured.xctestrun
  otherApps:
    - ./app_binaries/fake_counter_all_binaries/FakeCounterDuplicateApp.ipa
    - ./app_binaries/fake_counter_all_binaries/FakeCounterAppUITests-Runner.ipa
    - ./app_binaries/fake_counter_all_binaries/FakeCounterDuplicateAppUITests-Runner.ipa
suites:
  - name: "Mix XCTest and XCUITEST - Multiple test Apps are configured"
    devices:
      - name: ".*"
artifacts:
  download:
    when: always
    match:
      - "*.*"
    directory: ./